### ISSUE TITLE
improve support for mypy

### ISSUE THREAD

**Issue by delfick** [zcutlip/pyonepassword#48] opened 2022-10-30 10:07 UTC
Hello,

Is it possible for a release with a py.typed marker please?

Currently mypy complains with `Skipping analyzing "pyonepassword": module is installed, but missing library stubs or py.typed marker [dmypy]`

should be as straight forward as adding an empty `py.typed` file in the [pyonepassword](https://github.com/zcutlip/pyonepassword/tree/main/pyonepassword) folder and then changing package_data in [setup.py](https://github.com/zcutlip/pyonepassword/blob/9584d49/setup.py#L39) to be `package_data={'pyonepassword': ['py.typed', 'data/*']},`

**Comment by zcutlip** [comment] 2022-11-01 02:25
I'm happy to look into this. Please note that I don't use mypy and it isn't explicitly supported by `pyonepassword`. But what you're describing looks straightforward and I'll definitely investigate.

Also please know I'm in the process of getting the latest release out the door with #36 (item creation support), and that's my current priority. But I expect to have that wrapped up soon.

**Comment by zcutlip** [comment] 2022-11-01 02:28
Actually this looks simple enough that I should be able to roll it up into the next release.

**Comment by delfick** [comment] 2022-11-01 02:33
> Please note that I don't use mypy

right, is that why there's some type annotations, but not everywhere?

> Actually this looks simple enough that I should be able to roll it up into the next release.

Wicked, thanks :)

**Comment by delfick** [comment] 2022-11-02 03:54
> Yeah, I'm not as consistent as I'd like with type hinting.

gotta start somewhere! :)

**Comment by zcutlip** [comment] 2022-11-12 03:54
I'm sorry, I'm going to have to punt this to a later release. I added py.typed and a whole bunch of stuff caught on fire

Evidently there're some unintuitive aspects to type-hinting I don't fully understand. Plus some other design decisions I made that break various tools with mypy analysis gets turned on

Hopefully in the bug fix release after I get item creation out

**Comment by zcutlip** [comment] 2022-11-12 05:04
Actually @delfick, maybe you know what's causing one specific issue. I thought this was mypy related, but maybe not.

I have a sample project that imports things from pyonepassword. 

I'm getting an error from pylance in VSCode that `OPAbstractItem` is incompatible with `OPLoginItem` and can't be assigned. Screenshot attached.

`OPLoginItem` inherits directly from `OPAbstractItem`, so I don't see why that is.

I tried creating two simple, toy projects that do the same thing to isolate the issue, but I couldn't reproduce it there. 

Any ideas?

<img width="772" alt="Screenshot 2022-11-11 at 8 59 19 PM" src="https://user-images.githubusercontent.com/2158303/201458048-f21265a8-40b4-4987-afdf-3e47046fdd79.png">

**Comment by zcutlip** [comment] 2022-11-12 05:07
Incidentally this doesn't happen in example code & test code inside the `pyonepassword` project directory, which is why I'd never noticed before. Suspect that has something to do with it, maybe

**Comment by delfick** [comment] 2022-11-12 05:13
my guess is because a PyLoginItem has an interface that is a superset of
the abstractitem and so statically the abstract item doesn't have all the
things in a login item.

I'll have a look later when I'm at a computer and see how difficult it
would be to get at least mypy happy with the type declarations

**Comment by delfick** [comment] 2022-11-12 06:28
Looking at the code, I'd do this differently to make it easier to add types. I might rudely have a go at later for the fun of it hehehe.

In the meantime, the easiest thing you could do is

```
import typing as tp

item = tp.cast(OPLoginItem, op.item.get(options.item_id))
```

Though I'd add a method to do that

```
import typing as tp

T = tp.TypeVar("T", bound=OPAbstractItem)

class OP(...):
    def item_get_typed(self, typ: type[T], key: str) -> T:
        item = self.item_get(key)
        if not isinstance(item, typ):
            raise UnexpectedItem(...)
        return tp.cast(T, typ)
```

**Comment by zcutlip** [comment] 2022-11-12 06:33
So I ended up with the same solution last night, but this seems really unintuitive. It worked, but it didn't make a ton of sense to me.

Moreover, when I try to repro the same pattern in a simpler example, I don't have the issue.

Here are a couple screenshots from two toy projects, one importing from the other. In this example, there should be incompatibility between FooBase and FooSubB, but I get no complaints.

<img width="534" alt="Screenshot 2022-11-11 at 10 27 54 PM" src="https://user-images.githubusercontent.com/2158303/201460902-20d24dd0-991c-4069-a684-90bb4b8cf740.png">

<img width="564" alt="Screenshot 2022-11-11 at 10 28 09 PM" src="https://user-images.githubusercontent.com/2158303/201460910-5c4f04a9-65c8-48df-b1d0-dadcad52b818.png">

**Comment by delfick** [comment] 2022-11-12 06:49
generate_obj is the other way round, you're returning a superset that satisfies FooBase.

Also get_foo_sub_b_item isn't typed and so the type checker will ignore it (I assume pyright behaves like mypy for that).

So with
```
def get_foo_sub_b_item() -> int:
    ...
```

Then it complains because you're statically getting a type that doesn't have extra_function on it.

Also, the type of `_types` is `dict[str, FooBase]` because unless it's a typed dict, there can only be one value for the values and so it chooses a common denominator.

The thing to remember is that type hints are static whereas runtime is dynamic. So think of each class as it's own interface

So say we have this:

```
class Base:
    one: int
    two: int

class Sub1(Base):
    three: int

class Sub2(Base):
    four: int
```

That means statically you have these three interfaces

```
class Base:
    one: int
    two: int

class Sub1:
    one: int
    two: int
    three: int

class Sub2:
    one: int
    two: int
    four: int
```

So let's say you have a function:

```
def return_instance() -> Base:
    ...
```

and you use it like

```
instance: Sub2 = return_instance()
print(instance.four)
```

If return_instance returns a Sub1 it still satisfies Base because it has one and two on it. But it doesn't satisfy Sub2 because it doesn't have four on it. Which is why statically it doesn't make sense.

**Comment by delfick** [comment] 2022-11-12 06:52
Essentially the type checkers are designed with the liskov substitution principle in mind https://reflectoring.io/lsp-explained/ (I've only skimmed this article after searching for something that can explain liskov better than I can, it seems accurate)

**Comment by zcutlip** [comment] 2022-11-13 02:10
Thank you very much for the detailed explanation

It definitely makes sense to me that assigning a return value of a generalized type to a variable of a more specialized type is problematic. You don't *know* that the function returning returned the specific type you were expecting. So a linter saying "hey this may blow up if you get back a different kind of specialized object" makes sense

This concern was in the back of my mind all along. But VSCode only started complaining about it recently. In fact it only complains about it when I import `pyonepassword` from an external project. I get no such complaints from test code or example code, so I'd just assumed it somehow worked and I moved on

I don't quite understand what you mean by "generate_obj is the other way round"

`generate_obj()` is hinted to return FooBase, which is more general than what is being assigned to: FooSubB. I think this is the same pattern as `op.get_item()` returning `OPAbstractItem`, which is more general than what it is being assigned to: `OPLoginItem`

Regarding `_types`, that bit is a bit contrived. I was trying to simulate `OPItemFactory` which has a dictionary of item types.

Your mention of `pyright` gave me an insight. I `pip install`ed it and ran it on my toy example. I got this:

```
pyright 1.1.279
/Users/zach/Sync/Projects/src/use-typing-example/example.py
  /Users/zach/Sync/Projects/src/use-typing-example/example.py:6:12 - error: Expression of type "FooBase" cannot be assigned to declared type "FooSubB"
    "FooBase" is incompatible with "FooSubB" (reportGeneralTypeIssues)
```
...which is the exact problem I was getting with `op.item_get()`. I don't know why I'm not seeing this from pylance in vscode, but at least I'm seeing the same problem in the toy example.

Upon reflection, I think the bug is in my sample project importing `pyonepassword`. Assigning `op.item_get()` to a type that has been hinted as a specialized type is probably not the right thing to do

To my eye, there isn't something to do fix or do differently in `pyonepassword`, at least in this one case.

**Comment by delfick** [comment] 2022-11-13 05:08
> Thank you very much for the detailed explanation

You're welcome

> generate_obj() is hinted to return FooBase, which is more general than what is being assigned to: FooSubB

Its interface is not though. The interface of FooSubB has more on it than the interface of FooBase so as far as the callers of that function are concerned, the object returned only has what's defined on a FooBase, which doesn't contain the extra stuff that FooSubB defines.

**Comment by zcutlip** [comment] 2022-11-13 05:55
> the object returned only has what's defined on a FooBase, which doesn't contain the extra stuff that FooSubB defines

right right, that's what I mean by more general. FooSubB is more specialized that FooBase, having more stuff defined than FooBase.

Same with OPAbstractItem. OPLoginItem is more specialized, having additional things defined on it than OPAbstractItem.

I think this is the same pattern, and running `pyright` manually gives the same error. Not sure why I don't get the error when editing the toy project in VSCode, but I think we're in agreement here.

Anyway, this has really run off track. After the next release, I'll add py.typed and start fixing the other things that break (there were a bunch)

Thank you again for your help and your patience

**Comment by delfick** [comment] 2022-11-13 06:06
> right right, that's what I mean by more general. FooSubB is more specialized that FooBase, having more stuff defined than FooBase.

Yeap, so the function itself is fine. But that means you can't use what you get from it as a FooBaseB without casting it first to say that this behaves like a FooBaseB (though you should do runtime checks to make sure you are casting something that is indeed a FooBaseB).

> Anyway, this has really run off track

yay programming theory hahah

> Thank you again for your help and your patience

No probs :)

**Comment by zcutlip** [comment] 2022-11-21 19:03
@delfick I'm updating lots of `pyonepassword` to address `mypy` complaints. It's been pretty educational, and even has found a couple actual bugs. Plus a few things that wouldn't have been bugs, per se, but would have been gross crashes that I can now report up more gracefully to the caller

Anyway, I'm wondering if you can point me to any well-maintained, mypy-friendly projects? There are a few situations where the way to make `mypy` happy feels pretty contrived, and/or makes the code less readable. I'd love a project or two to use as reference for some tricker patterns

**Comment by delfick** [comment] 2022-11-21 19:21
ah cool! I'm not sure what are good references as the way I tend to pick up
things is by using the thing myself and learning things adhoc. I learnt the
most by doing https://github.com/delfick/strcs

I did start a little spike I have no intention of making into an actual
library to play with how I'd turn 1password info into objects,
https://github.com/delfick/py1pass but then I came across a blocker in how
strcs works and went through several layers of distraction. Also 1password
is a lot more complicated than I expected hahaha.

Do you have an example of some of those awkward typing moments?

**Comment by zcutlip** [comment] 2022-11-21 19:31
Okay, thanks! I'll look at those (I see you're making your own `pyonepassword` 😉)

I'll probably remember what some of the weird ones are when I go to committing these changes

**Comment by delfick** [comment] 2022-11-21 19:38
:)

my uncommitted changes involve the ability to get an item from onepassword
cli. However it relies on strcs being able to interpret generic structures,
which it currently doesn't. So I started to make that possible. Then I got
distracted by improving https://github.com/delfick/nose-of-yeti and then I
got distracted with another side project. I'll unwind eventually and point
out my approach when it works (with zero pressure to do anything with that
information)

**Comment by zcutlip** [comment] 2022-11-22 02:38
I guess one of the things I'm finding cumbersome is `mypy` complaining about typing for stuff that not only isn't API, but in fact is deeply internal. Not only would I rather not type-hint every little thing, but I'd rather keep some of these things somewhat opaque and not give any indication that they are to be used or how to do so.

For example, I have several registries where certain classes dynamically register themselves for use by a factory. The internals of the registries don't need to be type hinted. Here's an example (`OPItemFactory._TYPE_REGISTRY`):
https://github.com/zcutlip/pyonepassword/blob/e283cb78403af8c658496936da7d876f522d72c6/pyonepassword/op_items/_op_item_type_registry.py#L16

Is there a way to signal to `mypy` that these things are internal and should be ignored (without adding "type: ignore" comments all over)?

I wold think there would be a way for it to see that an attribute, method, or whatever is prefixed with an underscore, and treat it differently.

**Comment by delfick** [comment] 2022-11-22 10:19
I'd say the type hints are really useful for static analysis of your code.
It finds the kind of bugs that would otherwise require an obnoxious amount
of combinatory tests. So best to think of them more as a developer tool
more than a documentation tool. People usually get APIs from documentation
rather than code anyway. And those who don't won't be stopped by no type
hints!

As for your registry, you'd want an api that lets the user (whether that be
internal or external caller) specify the interface they expect back so that
your code can do that checking/casting for them.

Noting that checking against a typing.Protocol class can be adjacent to the
implementation heirarchy.

i.e. (am typing this on a phone, I think it looks right)

```
T = typing.TypeVar("T")

def get_from_registry(want: T, registry_key: str) -> T:
    got = registry[registry_key]
    if isinstance(got, want):
        return got
    else:
        raise ComputerSaysNo()

@typing.runtime_checkable
Class HasParticularMethod(typing.Protocol):
    def returns_stuff(self) -> int:
        ...

item = get_from_registry(HasParticularMethod, registry_key)

# item guanteed to have return_stuff(), yay for crosscutting concerns!


```

I found with most the dynamic things I've done, there's still some defined
shape to what is allowed, and now we have the tools to ask the computer to
check we're following those assumptions.

**Closed** 2022-11-25 00:44 UTC

**Comment by delfick** [comment] 2022-11-25 10:50
I had a quick skim and left some comments. I feel static checking isn't built for collaborative mixins that require developer co-ordination :p

**Comment by zcutlip** [comment] 2022-11-25 17:10
> I had a quick skim and left some comments. I feel static checking isn't built for collaborative mixins that require developer co-ordination :p

thanks for the feedback! I made some changes

I also thoroughly horked up merging last night, so I'm hoping to get that fixed this morning. Stay tuned for more chaos

**Comment by zcutlip** [comment] 2022-11-25 17:15
Also, just want to say I've learned a ton from this GH issue. Thanks for your help

**Comment by delfick** [comment] 2022-11-27 02:09
> Also, just want to say I've learned a ton from this GH issue. Thanks for your help

You're welcome !

> Stay tuned for more chaos

ehehhehe

**Comment by zcutlip** [comment] 2022-11-27 02:20
don't know if you saw, but v3.3.4 is out and available in pypi

**Comment by delfick** [comment] 2022-11-27 12:12
oooh nice, thanks, seems I just need to figure out the new way of doing

```
from pyonepassword.api.decorators import op_register_item_type
from pyonepassword.op_items._op_items_base import OPAbstractItem


@op_register_item_type
class OPDatabase(OPAbstractItem):
    CATEGORY = "DATABASE"

    def __init__(self, item_dict):
        super().__init__(item_dict)

    @property
    def password(self) -> str:
        return self.field_value_by_id("password")
```

**Comment by zcutlip** [comment] 2022-11-28 04:22
In the last release I exported `OPAbstractItem` in `pyonepassword.api.object_types`, so you should be able to import it from there

let me know (in a separate issue, please) if you have any troubles making it work.

Also if there are additional item times that would be useful (such as database) please file a GitHub issue.

I intend over time to support as many as possible. Many of them are really straightforward and I can add with minimal effort. A few are really complicated and I don't mind adding, but could take a while.
