### ISSUE TITLE
call to create item never returns?

### ISSUE THREAD

**Issue by zestysoft** [zcutlip/pyonepassword#169] opened 2023-11-09 00:55 UTC
Heya, after using biometric authentication through the module and handling a OPItemGetException exception looking for an item that doesn't exist in 1password, a subsequent call to create that item returns in a call that never returns.

I've debugged it down to the cls._run( function which calls the op binary:
`'op', '--format', 'json', 'item', 'create', '--template', '/var/folders/1r/_9dfjlnd7bq1432vg9h6crh00000gq/T/tmpzkizz7sr'`

however if I open a terminal and issue that command myself, I'm presented to authentication with the biometrics gui prompt again and after authenticating I see the appropriate json output of a successful execution.  Any idea what could be holding up the op binary?  Is it prompting for information or something that's not getting passed back to me?

**Comment by zcutlip** [comment] 2023-11-09 04:10
Hey, I hate this is happening to you, but thanks for rolling up your sleeves and trying to get to the bottom of it.

First off, can you share the following details?

- `pyonepassword` version
- `op` version
- operating system and version (I'm guessing you're on macOS based on the temp directory structure) 

Also, there are a couple things to do to get a bit more diagnostic output.

can you do:

```python
from pyonepassword.logging import console_debug_logger
# enable error output to console
os.environ['LOG_OP_ERR'] = "1"

# enable debug logging
logger = console_debug_logger("logger-name")
# pass logger= in addition to whatever other kwargs you're passing to OP
op = OP(logger=logger)
```
then perform your operation with that `OP` object, and you should get more console output.

Please do that and share the output. 

I suspect/am worried what's happening is the `op` CLI is prompting for authentication on the console but `pyonepassword` is consuming that output because it expects the JSON for the created item, so it doesn't let the interactive prompt be displayed. In which case it blocks forever. I've tried to avoid this situation, but I've often worried it could happen.

Looking forward to what you're able to share.

**Comment by zcutlip** [comment] 2023-11-09 18:55
I want to try to reproduce your scenario, so if you can provide as much of the following information as you can, it would really help:

- operating system and version?
- could you show me the exact instantiation of `OP()` with all args?
- Can you share *all* the console output from when you first instantiate `OP()` to when it hangs?
- Are you doing this via a script or an interactive REPL like ipython?
  - Or some other way (e.g., running within a vscode or vim session?)
- Are you authenticating with `op` outside of your Python script/environment? If so, how?
  - e.g., are you doing something like `eval $(op signin)` etc
  - are you just running an `op` query and letting it prompt for authentication?
- I'm assuming you have the 1Password desktop app installed, since you say you get a biometric prompt from `op`. Is this correct?
- Do you have more than one 1Password account configured? 
  - I have my personal account and my open source project's account, so I'm often prompted on the console to choose and account
  - Is this the same for you?
- If *possible* can you try on an older version of `op` and tell me if it reproduces?
  - here's a link to older versions: https://app-updates.agilebits.com/product_history/CLI2#v2210002
  - You can unzip to anywhere and pass the location of the op binary to `OP()`, like:
```
In [2]: op_path = "./2.21.0/arm64/op"

In [3]: op = OP(op_path=op_path)
```

What I *suspect* is that `op` has changed its `whomi` behavior in 2.22.0. I call `whoami` before each operation in hopes of catching a situation that would cause an interactive prompt, but this may no longer be working as expected.

**Comment by zestysoft** [comment] 2023-11-09 19:43
- MacOS Sonoma 14.1
- The original instantiation was just the simple `op = OP()`  I did add your logger=logger bit after though.
- python script that I'm running through the PyCharm debugger.  python version is 3.9
- Yes -- I use op in .zshrc to populate a number of environment variables that contain things like tokens.  `ps` shows `op daemon` is running right now for instance.  I get the biometric auth prompt when I open a terminal window, and then, apparently, the default setting is to cache that for a short duration.
- Yes, I have 1Password for Mac 8.10.18 installed
- I just have the one account.
- I'll try the older binary and get back to you
- I don't believe whoami is where the problem is.  When the python script hangs, and I do a ps of the running processes, it's the one to create that's sitting there:

```
ps aux|egrep -o "op\s.*"
op --format json item create --template /var/folders/1r/_9dfjlnd7bq1432vg9h6crh00000gq/T/tmpedv6rtph
op daemon
```

Here is the slightly redacted output:

```
Running: op --version
Running: op --format json account list
Running: op signin --raw
Running: op --format json whoami
Signed in as User ID: *********************JUQJM
Running: op --format json whoami
Running: op --format json item get 'Slack App Client ID and Secret'
Running: op --format json whoami
Running: op --format json item get 'Slack Token'
'op' command error: [ERROR] 2023/11/09 11:30:29 "Slack Token" isn't an item. Specify the item with its UUID, name, or domain.
No token found, please visit the URL below to authorize this app to your Slack workspace.
https://slack.com/oauth?client_id=redacted&scope=&user_scope=channels%3Aread%2Cchannels%3Ahistory%2Cgroups%3Aread%2Cgroups%3Awrite%2Cusers%3Aread%2Cchannels%3Awrite&redirect_uri=&state=&granular_bot_scope=1&single_channel=0&install_redirect=oauth&tracked=1&team=1
Please copy-paste the OAuth token here: >? redacted token
Running: op --format json whoami
Running: op --format json item create --template /var/folders/1r/_9dfjlnd7bq1432vg9h6crh00000gq/T/tmpedv6rtph
```

The script doesn't do much up to this point -- It auths into op, successfully pulls one secret for the Slack stuff, and then attempts to pull a slack token if one exists.  I probably should use a different method to check if the item exists instead of relying on a get item exception, but in the exception handler I've got code that asks the user for the generated token and then attempts to create the missing item in 1password -- it's at that point that it hangs.

**Comment by zestysoft** [comment] 2023-11-09 19:50
FWIW, this is my .zshrc.1password file that is sourced at the top of .zshrc.  It pulls three different tokens from 1password and caches the results for a short duration so that when I open a number of other panes in tmux, I don't get re-prompted to auth each time:

```
# Define the path to the temporary environment file
tmp_env="$TMPDIR/myenv_$(id -u)"

# Check if the file exists and is less than 60 seconds old
if [[ ! -f "$tmp_env" ]] || [[ $(date +%s) -gt $(($(stat -f "%m" "$tmp_env") + 60)) ]]; then
  # Create or truncate the file
  : >| "$tmp_env"

  typeset -A ONEPASSVARS

  # associative array storing variable name and associated 1pass secret ID
  ONEPASSVARS[GITHUB_TOKEN]=$(op item get GITHUB_TOKEN --format=json|jq -r '.id')
  ONEPASSVARS[BUNDLE_GEM__FURY__IO]=$(op item get BUNDLE_GEM__FURY__IO --format=json|jq -r '.id')
  ONEPASSVARS[ARTIFACTORY_READ_TOKEN]=$(op item get ARTIFACTORY_READ_TOKEN --format=json|jq -r '.id')

  # Populate the file with environment variables
  for VAR in ${(k)ONEPASSVARS}; do
    value=$(op item get $ONEPASSVARS[$VAR] --fields Password)
    echo "export $VAR='$value'" >> "$tmp_env"
  done

  # Background process to remove the file after 60 seconds
  # Disable job control
  setopt NO_MONITOR

  # Start the background process
  ( sleep 60 && rm -f "$tmp_env" ) >/dev/null 2>&1 &

  # Re-enable job control if needed
  setopt MONITOR


fi

# Source the temporary file
set -a
source "$tmp_env"
set +a
```

**Comment by zcutlip** [comment] 2023-11-09 20:08
okay, thank you for sharing. I'm going to dig into this; I'm extremely interested in getting to the bottom of it. But for the time being I need to get back to my day job that pays the bills. 🤣

> I don't believe whoami is where the problem is. When the python script hangs, and I do a ps of the running processes, it's the one to create that's sitting there:

Sorry I meant if there is going to be an interactive prompt that blocks, `whoami` should either trigger that or fail completely, so that the next operation doesn't hang forever. But from what I'm seeing and what you've told me, there's no reason the `item create` should be resulting in an interactive authentication prompt.

I'll jump in the 1Password developer's slack and see if any engineers are around who can weigh in.

I may end up creating a special branch that has some additional diagnostic capability. In that case you be willing to work off a branch?

**Comment by zestysoft** [comment] 2023-11-09 20:19
Actually I just ran the same exact script straight from the command line and it works fine there.  There must be something about running the code in PyCharm that is causing this.  I tried both "Run Main" and "Debug Main" and both hang.

Very strange, but I think we can close this issue.  Thanks for your time!  I'll ping PyCharm's support and see what's up.

**Comment by zcutlip** [comment] 2023-11-09 20:32
I'm happy to leave the issue open until you hear from PyCharm. If there's something I can add to `pyonepassword` to make things play nicely in your IDE, I'd be interested in knowing.

**Comment by zcutlip** [comment] 2023-11-13 19:21
Hey @zestysoft just checking if you've heard anything from PyCharm support on this.

**Comment by zcutlip** [comment] 2023-11-15 03:37
I heard back from a 1Password engineer and they said they've seen this sort of thing happen before when `op` is running in some environments, and it's a known issue.

In particular, under some circumstances, `op` incorrectly thinks it has data on `stdin` and then blocks forever trying to read that input.

Something that I think will help mitigate this situation (though the bug is with `op`) is to pipe the new item template to `op` rather than write it out to a temp file and reference it via `--template`

When I first added item creation I believe this wasn't possible, but I should add it now and drop support for `op` versions that don't support it.

**Comment by zcutlip** [comment] 2023-11-15 03:42
Created #172

**Comment by zestysoft** [comment] 2023-11-15 04:09
I haven't yet reached out to them.  I just closed a very frustrating ticket with them that they were unable to resolve but which thankfully fixed itself.

I figure there's some kind of issue with how the ide redirects / captures the stdout and stdin, but I don't have much faith in their willingness to look that deeply into this tbh.  I was already on the fence to switch over to Visual Code, and am looking into that now, esp since I don't just code in python. If you really do want this however, I'll open a ticket for ya.

One thing I was curious about with the op executable -- I noticed that after it runs, it leaves a daemon running that's listening on a socket.  I wonder how difficult it would be in python to duplicate what the op executable must be doing to communicate through that socket in subsequent runs?

```
sudo lsof|grep "88708"|grep "unix"
op        88708             user    4u     unix 0xcdb62577f94f771d         0t0                      /Users/user/.config/op/op-daemon.sock
```

**Comment by zcutlip** [comment] 2023-11-15 04:41
No worries already opened the ticket here: https://github.com/zcutlip/pyonepassword/issues/169#issuecomment-1811761386

> One thing I was curious about with the op executable -- I noticed that after it runs, it leaves a daemon running that's listening on a socket.

So that's the caching daemon, and as I understand it is the component that's actually responsible for talking to the 1Password cloud. I'm not sure where authentication happens; I suspect it happens in `op` (or between `op` and the desktop app if that's turned on) and is then passed through the daemon. I suspect making a stand-in `op` to talk to the daemon would be quite involved.

Anyway, getting item creation converted to stdin instead of reading from temp file should be pretty straightforward, but I've got a couple issues in front of that I need to get to.

Let me know (open a discussion) if you give vscode a try and need help; that's what I've been using for the last 5 or so years. 

Going to go ahead and close this issue.

**Closed by zcutlip** 2023-11-15 04:41 UTC
