### ISSUE TITLE
pyonepassword should not pass session token to 1password-cli >= 1.0.0 over stdin

### ISSUE THREAD

**Issue by darkdreamingdan** [zcutlip/pyonepassword#7] opened 2020-06-02 20:12 UTC
Unfortunately this library doesn't work with 1password-cli 1.0.0.  It's because 1password have seemingly broken their STDIN auth functionality.  It means this library fails to sign in and doesn't work.

Downgrading to 1password-cli 0.10.0 fixes the issue.  I've gone ahead and reported this as a bug to the 1password team, but workarounds are to set the `OP_SESSION_<domain>` environment variable, or to use the `--session` command line flag in commands.

**Comment by zcutlip** [comment] 2020-06-02 23:39
Okay, thanks for the report. I'll have a look at it asap.

**Comment by darkdreamingdan** [comment] 2020-06-03 11:42
Yeah maybe 1password can also fix this on their side too.  I submitted it via the geneeral customer support because i couldn't find a bug tracker, so who knows how long it'll take for them to do something.

**Comment by fkling** [comment] 2020-06-03 14:52
Hi everyone!

I'm a software engineer working on the 1Password command line tool and @darkdreamingdan brought this issue to our attention.

It was actually a deliberate decision to remove this functionality, so that we can use stdin for more useful features in the future (e.g. `op get item < listofitems.txt`). We were under the impression that this feature was never publicly documented but clearly we were wrong about that. Otherwise we would have communicated this change in a better way. It was certainly not our intention to unnecessarily break things.

As @darkdreamingdan already mentioned, going forward the session token should be passed via `--session` instead.

If I can be of any other assistance, please let me know!

**Comment by zcutlip** [comment] 2020-06-03 16:06
Hi @fkling, thanks for the update and clarification, and for the great work on `op`! Let me know if there's a better medium to talk about this issue.

Unfortunately, this change means there's no way to use `op` non-interactively. Clearly we can pass a session token once we have it, but we can't get the token to begin with without interactively entering the password at the console. I have some ideas, however. I wonder if any of them would work:

- During `op signin` I believe we wouldn't be using stdin in the way you describe. Could the `signin` command still take the password over stdin if available?
- If the above is impractical, I know there are some utilities that provide an option to specify credentials are to be found on stdin (I'm drawing a blank, but I know I've used them). Could there be something like this for the  the `signin` command, like `--passwd-stdin` (I'm terrible at naming things!) to explicitly enable that behavior?

**Comment by zcutlip** [comment] 2020-06-03 16:11
Just a follow up: I realize using op non-interactively is very edge-case. And doing so necessarily implies storing your 1P creds somewhere. But there are secure storage mechanisms that are suitable and would support. One example would be an ansible vault, enabling `op` to be used programmatically in that context.

**Comment by darkdreamingdan** [comment] 2020-06-03 16:29
> Just a follow up: I realize using op non-interactively is very edge-casey. And doing so necessarily implies storing your 1P creds somewhere. But there are secure storage mechanisms that are suitable and would support non-interactive use. One example would be an ansible vault, enabling `op` to be used programmatically in that context.

Hmm, passing session tokens in stdin is indeed not working, however i can still signin with stdin:

```
dan@1823:~$ op --version
1.0.0
dan@1823:~$ echo $password | op signin
export OP_SESSION_domain="FXX9Dfasdv8VP76fD5lmWG8wBFHAvetuga3Yy3OQSnQ"
# This command is meant to be used with your shell's eval function.
# Run 'eval $(op signin babylonhealth)' to sign in to your 1Password account.
# Use the --raw flag to only output the session token.
```

**Comment by zcutlip** [comment] 2020-06-03 16:35
I may have misunderstood then. If the issue is that session token is no longer accepted over stdin, and requires `--session`, that's an easy fix. If the password can still be passed over stdin, I think we'll be in good shape.

**Comment by fkling** [comment] 2020-06-04 22:20
Yeah, sorry, I could have been clearer on this: The `signin` command itself didn't change. It still accepts the Master Password via stdin.
We have removed reading the *session token* from stdin from every other command, because we want to use stdin for something more useful depending on the command. But for the `signin` command, accepting the Master Password via stdin is exactly the right thing to do :slightly_smiling_face:

**Comment by zcutlip** [comment] 2020-06-04 22:55
Awesome. Thanks @fkling! And thanks again for `op`.

**Comment by cacoyle** [comment] 2020-06-05 17:30
I think this might do the trick.  I wrote another patch that extended argv with`['--session', self.token]` in `_run()`, but unless `op` is masking the session value from stdin, it could be intercepted by an unprivileged user from the process table.

**Comment by zcutlip** [comment] 2020-06-05 20:05
> but unless `op` is masking the session value from args, it could be intercepted by an unprivileged user from the process table.

Good catch. I did verify the session token is visible in `ps -ef`, so env variable looks like the way to go.

**Comment by zcutlip** [comment] 2020-06-05 21:55
Okay, I merged #8 into [branch fix-session-token](/zcutlip/pyonepassword/tree/fix-session-token). Can people give that a try?

API-breaking change: `account_shorthand` is now a require argument to `OP()`.

**Comment by cacoyle** [comment] 2020-06-05 22:33
Works here.  If I'm following along,  having an `account_shorthand` param might've been required to support multiple accounts anyway.  Is that right?

If you wanted to preserve some level of backwards compatibility, at least for single-account use, you could maybe key off `latest_signin` from `~/.op/config`

```
from pathlib import Path
import json

config_path = '/'.join([str(Path.home()), '.op', 'config'])

with open(config_path, 'r') as op_config:
    config = json.loads(op_config.read())

print(config['latest_signin'])
```

**Comment by zcutlip** [comment] 2020-06-05 23:54
Yes, you are correct: we would require the shorthand in order to support multiple accounts, so it's nice that we get that for free in the process.

Your idea about parsing `~/.op/config` is a good one, and I'll think about it. My concerns with it are: 

- there's no guarantee that it lives there (check out the discussion forums for questions about relocating it)
- the format or contents of the config are private to `op` and could change at any time

I suppose we could use it on a best-effort basis and raise a meaningful exception if we haven't been provided and are unable to look up the shorthand?

**Comment by cacoyle** [comment] 2020-06-06 01:14
IMO using it as a best-effort for backwards compatibility and raising an understandable exception makes sense.

If there's support for relocating the config on the op side in the future I think you could add that as an `__init__` arg with a default value of `~/.op/config` (or whatever's sensible per platform) and maintain consistency.

**Comment by zcutlip** [comment] 2020-06-14 20:48
Okay, `account_shorthand` is now an optional kwarg to `OP()`. If not provided, we'll attempt to located it from:

- `$XDG_CONFIG_HOME/.op/config`
- `~/.op/config`

This is per discussion at:
https://discussions.agilebits.com/discussion/comment/562181/#Comment_562181

If the account shorthand isn't provided, and we can't look it up, we raise:

- `OPConfigNotFoundException` if the config can't be located or can't be opened
- `OPSigninException` if the config doesn't contain an account shorthand

Give this a try in [branch fix-session-token](https://github.com/zcutlip/pyonepassword/tree/fix-session-token)

**Closed** 2020-06-24 17:41 UTC
