### ISSUE TITLE
How do I edit items?

### ISSUE THREAD

**Issue by GadgetGeekNI** [zcutlip/pyonepassword#141] opened 2023-07-26 14:01 UTC
Sorry for the dumb question, 

I went over the docs and code and I can't figure out how to do an op.item_edit 

Is this still not an implemented feature?

**Comment by zcutlip** [comment] 2023-07-26 15:33
Not a dumb question, and the short answer is no this is not supported in `pyonepassword`

The slightly longer version is item editing with `op` works very differently from operations like `get`, `create`, and `delete`. Those operations work with JSON as either output or input to the operation, which is what `pyonepassword` is designed around. In contrast editing has complex CLI syntax, and translating between that and a generic python API is not straightforward.

I don't foresee arbitrary item editing, but it's possible I'll be able to add limited edit operations like password changes.

There's an ongoing discussion here:
https://github.com/zcutlip/pyonepassword/discussions/140

**Comment by GadgetGeekNI** [comment] 2023-07-27 07:31
Thank you for your response! 

In the interim, I would guess that the cadence for updating a 1p entry is to first get & ensure it exists, if exist then delete and create secret with new credentials? If not exist, then create?

I was looking into OnePassword Connect and now with service accounts having come out we are just looking at integrating it into some automated password rotation scripts.

Thank you!

**Comment by zcutlip** [comment] 2023-07-28 16:23
Sorry for the slow response; I'm traveling on vacation this week so my schedule's a little out of whack.

Yes, unfortunately making edits with `pyonepassword` means doing the following operations:

- get the item
- change the item locally
- delete the original
- create a new item

As discussed in #140, I am looking into supporting limited edit operations such as changing a password etc. So hopefully that will be in line with what you need as well. Feel free to chime in on that discussion. Sharing example JSON is always helpful too.

Cheers!
Zach

**Comment by zcutlip** [comment] 2023-08-02 03:55
going to close this as a duplicate of #143 which is where I'm doing the work.

**Comment by zcutlip** [comment] 2023-08-02 03:57
working on this in #143 so closing this as a duplicate

Duplicate of #143

**Comment by zcutlip** [comment] 2023-08-02 03:59
Duplicate of #143

**Closed by zcutlip** 2023-08-02 03:59 UTC
